ruby:
  dockerfile: ./docker/ruby/Dockerfile
  build: .
  volumes:
    - ./:/project
  ports:
    - 2300:2300
  links:
    - postgres
  command: bundle exec hanami server --host=0.0.0.0
postgres:
  dockerfile: Dockerfile
  build: ./docker/postgres
  volumes:
    - data:/var/lib/postgresql/data
  ports:
    - 5432:5432
  env_file: .env.pg
